[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = { version = "0.10.2", default-features = false }
ort = "=2.0.0-rc.9"
ndarray = "0.16.1"
image = "0.25.6"

[profile.release]
lto = true

[lib]
name = "rust"
crate-type = ["cdylib"]
